# Generated by Django 4.1.7 on 2023-04-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0003_alter_review_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("movies", models.ManyToManyField(to="streaming.movie")),
            ],
        ),
    ]
